#!/usr/bin/env zsh

req_dirs=("/home/$USER/Work" "/home/$USER/.config/i3/layouts" "/home/$USER/.config/i3status" "/home/$USER/.bin")

for dir in ${req_dirs[@]}; do
	if [ ! -d $dir ]
	then
		echo "creating $dir"
		mkdir -p $dir
	else
		echo "$dir already exists"
	fi
done
